import { Member, Match, Tournament, NewsPost, JoinRequest, ClubSettings } from '../types';

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'm1',
    full_name: 'Hoàng Mạnh Cường',
    nickname: 'Cường Chủ Tịch',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    phone: '0988.112.233',
    email: 'cuong.hm@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'admin',
    hand: 'right',
    paddle: 'Joola Perseus 3S 16mm',
    preferred_side: 'left',
    join_date: '2024-01-10',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['👑 Chủ Tịch CLB', '🏆 Ban Quản Trị CLB'],
    bio: 'Chủ tịch CLB Pickleball Friends, điều hành và phát triển phong trào tập luyện thi đấu 2v2.',
  },
  {
    id: 'm2',
    full_name: 'Hương Xoăn',
    nickname: 'Hương Xoăn',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    phone: '0912.334.455',
    email: 'huong.xoan@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'admin',
    hand: 'right',
    paddle: 'Selkirk Vanguard Control Invikta',
    preferred_side: 'right',
    join_date: '2024-01-15',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['⭐ Ban Điều Hành', '⚡ Nữ Tướng Pickleball'],
    bio: 'Ban điều hành CLB, phụ trách kết nối thành viên và tổ chức các sự kiện thi đấu nội bộ.',
  },
  {
    id: 'm3',
    full_name: 'Loan',
    nickname: 'Loan BĐH',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    phone: '0988.445.566',
    email: 'loan.bdh@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'admin',
    hand: 'right',
    paddle: 'Paddletek Bantam TKO-C',
    preferred_side: 'flexible',
    join_date: '2024-01-15',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['⭐ Ban Điều Hành', '🎯 Tay Vợt Bền Bỉ'],
    bio: 'Ban điều hành CLB, điều phối hoạt động sân bãi và phong trào rèn luyện kỹ thuật.',
  },
  {
    id: 'm4',
    full_name: 'Ngọc Tôm',
    nickname: 'Ngọc Tôm',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    phone: '0977.556.677',
    email: 'ngoctom.kt@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'admin',
    hand: 'right',
    paddle: 'Six Zero Double Black Diamond',
    preferred_side: 'right',
    join_date: '2024-02-01',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['💼 Kế Toán / Thủ Quỹ CLB', '🏸 Tay Lưới Vàng'],
    bio: 'Kế toán / Thủ quỹ CLB Friends, quản lý quỹ và công tác hậu cần các giải đấu.',
  },
  {
    id: 'm5',
    full_name: 'Phạm Linh',
    nickname: 'Linh Phó CT',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    phone: '0933.667.788',
    email: 'linh.pham@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'admin',
    hand: 'left',
    paddle: 'CRBN 1X Power Series 16mm',
    preferred_side: 'left',
    join_date: '2024-01-10',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🎖️ Phó Chủ Tịch CLB', '🔥 Chiến Thần Tốc Độ'],
    bio: 'Phó Chủ tịch CLB Pickleball Friends, phụ trách phát triển chuyên môn và tổ chức giải đấu.',
  },
  {
    id: 'm6',
    full_name: 'Đặng Quyết',
    nickname: 'Quyết Đặng',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
    phone: '0944.778.899',
    email: 'quyet.dang@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'Gearbox Pro Power Elongated',
    preferred_side: 'left',
    join_date: '2024-02-15',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🚀 Cú Đánh Uy Lực'],
    bio: 'Đam mê thi đấu đôi, sở trường những cú smash uy lực cuối sân.',
  },
  {
    id: 'm7',
    full_name: 'Đào Minh',
    nickname: 'Minh Đào',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    phone: '0966.889.900',
    email: 'minh.dao@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'Engage Pursuit Pro EX',
    preferred_side: 'flexible',
    join_date: '2024-03-01',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🎯 Bậc Thầy Dinking'],
    bio: 'Điều bóng kiên trì gài góc hiểm, lối đánh chắc chắn và hiệu quả.',
  },
  {
    id: 'm8',
    full_name: 'Duy Nguyen',
    nickname: 'Duy Nguyễn',
    avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    phone: '0911.990.011',
    email: 'duy.nguyen@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'member',
    hand: 'right',
    paddle: 'Franklin Sports Pro',
    preferred_side: 'right',
    join_date: '2024-03-10',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['⚡ Phản Xạ Nhạy Bén'],
    bio: 'Di chuyển linh hoạt, hỗ trợ đồng đội bọc lót tốt trong các pha bóng nhanh.',
  },
  {
    id: 'm9',
    full_name: 'Giang',
    nickname: 'Giang Pickle',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400',
    phone: '0922.112.233',
    email: 'giang@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'member',
    hand: 'right',
    paddle: 'Head Radical Elite',
    preferred_side: 'flexible',
    join_date: '2024-03-15',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🛡️ Bức Tường Kitchen'],
    bio: 'Thích lối chơi đồng đội gắn kết, luôn sẵn sàng ra sân giao lưu học hỏi.',
  },
  {
    id: 'm10',
    full_name: 'Hạnh',
    nickname: 'Hạnh Pickle',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    phone: '0933.223.344',
    email: 'hanh@friends.club',
    dupr_rating: 3.00,
    elo_points: 1000,
    role: 'member',
    hand: 'right',
    paddle: 'Selkirk Luxx Control Air',
    preferred_side: 'right',
    join_date: '2024-03-20',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🌸 Tay Vợt Nữ Năng Động'],
    bio: 'Tham gia tập luyện đều đặn, tích cực trong mọi hoạt động của CLB.',
  },
  {
    id: 'm11',
    full_name: 'Hoang Diep',
    nickname: 'Hoàng Điệp',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    phone: '0944.334.455',
    email: 'hoangdiep@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'ProXR Signature Series',
    preferred_side: 'left',
    join_date: '2024-04-01',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🌀 Xoáy Topspin'],
    bio: 'Cú drive topspin cuộn bóng khó chịu, phát bóng xoáy ổn định.',
  },
  {
    id: 'm12',
    full_name: 'V Hoang Jp',
    nickname: 'Vũ Hoàng (JP)',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    phone: '0955.445.566',
    email: 'vhoang.jp@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'JOOLA Collin Johns Scorpeus 3S',
    preferred_side: 'flexible',
    join_date: '2024-04-05',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['👟 Kỹ Thuật Erne'],
    bio: 'Lối đánh thông minh, nhãn quan chiến thuật tốt và các pha xử lý lưới tinh tế.',
  },
  {
    id: 'm13',
    full_name: 'Dũng Hoạ',
    nickname: 'Dũng Họa',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    phone: '0966.556.677',
    email: 'dung.hoa@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'Joola Perseus 3S 16mm',
    preferred_side: 'left',
    join_date: '2024-01-20',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🏸 Chủ Sân Nhiệt Huyết', '🔥 Smash Uy Lực'],
    bio: 'Đóng góp to lớn cho sân bãi CLB Friends tại Eko Lake, luôn tràn đầy năng lượng thi đấu.',
  },
  {
    id: 'm14',
    full_name: 'Dương Tuấn Anh',
    nickname: 'Tuấn Anh',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    phone: '0977.667.788',
    email: 'tuananh.duong@friends.club',
    dupr_rating: 3.38,
    elo_points: 1150,
    role: 'member',
    hand: 'right',
    paddle: 'CRBN 1X Power Series',
    preferred_side: 'left',
    join_date: '2024-02-10',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['⚡ Cú Smash Sấm Sét', '👑 Top 1 ELO CLB'],
    bio: 'Tay smash sắc bén, tấn công dồn dập khiến đối thủ khó phòng thủ.',
  },
  {
    id: 'm15',
    full_name: 'Hiệu Hơn',
    nickname: 'Hiệu Hơn',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
    phone: '0988.778.899',
    email: 'hieu.hon@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'member',
    hand: 'right',
    paddle: 'Six Zero DBD',
    preferred_side: 'right',
    join_date: '2024-03-05',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🎯 Chiến Binh Bền Bỉ'],
    bio: 'Bền bỉ trong từng đường bóng, tinh thần thể thao cao thượng.',
  },
  {
    id: 'm16',
    full_name: 'Lê Hà',
    nickname: 'Hà Lê',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    phone: '0903.998.877',
    email: 'ha.le@friends.club',
    dupr_rating: 3.00,
    elo_points: 1000,
    role: 'member',
    hand: 'right',
    paddle: 'Paddletek Bantam',
    preferred_side: 'right',
    join_date: '2024-03-12',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🛡️ Phòng Ngự Chắc Chắn'],
    bio: 'Khả năng cứu bóng và gài góc rất dẻo dai, thi đấu nhiệt tình.',
  },
  {
    id: 'm17',
    full_name: 'Nguyễn Hằng',
    nickname: 'Hằng Nguyễn',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    phone: '0912.887.766',
    email: 'hang.nguyen@friends.club',
    dupr_rating: 3.00,
    elo_points: 1000,
    role: 'member',
    hand: 'right',
    paddle: 'Selkirk Vanguard Control',
    preferred_side: 'flexible',
    join_date: '2024-03-18',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🌸 Hoa Khôi Sân Đấu'],
    bio: 'Vui vẻ hòa đồng, kỹ thuật dink bóng mềm mại và chuẩn xác.',
  },
  {
    id: 'm18',
    full_name: 'Nguyễn Minh',
    nickname: 'Minh Nguyễn',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    phone: '0923.776.655',
    email: 'minh.nguyen@friends.club',
    dupr_rating: 3.00,
    elo_points: 1000,
    role: 'member',
    hand: 'right',
    paddle: 'Engage Pursuit Pro',
    preferred_side: 'left',
    join_date: '2024-03-25',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['⚡ Tốc Độ & Linh Hoạt'],
    bio: 'Thích nhịp độ trận đấu nhanh, chủ động tấn công trên lưới.',
  },
  {
    id: 'm19',
    full_name: 'Nhà Xe Tuấn Liên',
    nickname: 'Tuấn Liên',
    avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    phone: '0934.665.544',
    email: 'tuanlien@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'member',
    hand: 'right',
    paddle: 'Joola Perseus 16mm',
    preferred_side: 'flexible',
    join_date: '2024-02-01',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🚚 Nhà Tài Trợ Vàng', '💪 Thể Lực Dồi Dào'],
    bio: 'Nhà tài trợ đồng hành cùng phong trào thể thao Pickleball Friends Thái Nguyên.',
  },
  {
    id: 'm20',
    full_name: 'Ninh Van Quyen',
    nickname: 'Quyền Ninh',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    phone: '0945.554.433',
    email: 'quyen.ninh@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'ProXR Signature',
    preferred_side: 'right',
    join_date: '2024-03-01',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🎯 Giao Bóng Chuẩn Xác'],
    bio: 'Phát bóng xoáy khó chịu và khả năng đọc tình huống trận đấu rất tốt.',
  },
  {
    id: 'm21',
    full_name: 'Phạm Ngọc Tâm',
    nickname: 'Tâm Phạm',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    phone: '0956.443.322',
    email: 'tam.pham@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'member',
    hand: 'right',
    paddle: 'Franklin Sports Pro',
    preferred_side: 'flexible',
    join_date: '2024-03-08',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🔥 Tay Vợt Tấn Công'],
    bio: 'Lối đánh mạnh mẽ, luôn tạo áp lực liên tục lên phần sân đối phương.',
  },
  {
    id: 'm22',
    full_name: 'Tâm Mobile',
    nickname: 'Tâm Mobile',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    phone: '0967.332.211',
    email: 'tam.mobile@friends.club',
    dupr_rating: 3.00,
    elo_points: 1000,
    role: 'member',
    hand: 'right',
    paddle: 'Six Zero Double Black Diamond',
    preferred_side: 'left',
    join_date: '2024-02-15',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['📱 Chiến Binh Công Nghệ', '⚡ Phản Tạt Lưới'],
    bio: 'Kỹ thuật tốt, phản xạ nhanh và tinh thần thi đấu hết mình vì đồng đội.',
  },
  {
    id: 'm23',
    full_name: 'Thanh Tuyến',
    nickname: 'Tuyến Thanh',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    phone: '0978.221.100',
    email: 'tuyen.thanh@friends.club',
    dupr_rating: 3.25,
    elo_points: 1100,
    role: 'member',
    hand: 'right',
    paddle: 'Selkirk Vanguard',
    preferred_side: 'right',
    join_date: '2024-03-20',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🛡️ Lối Đánh Điềm Đạm'],
    bio: 'Điềm đạm trên sân, khả năng xử lý bóng bền bỉ và kiểm soát nhịp độ tuyệt vời.',
  },
  {
    id: 'm24',
    full_name: 'Thầy Tân',
    nickname: 'Thầy Tân',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    phone: '0989.110.099',
    email: 'thay.tan@friends.club',
    dupr_rating: 3.00,
    elo_points: 1000,
    role: 'member',
    hand: 'right',
    paddle: 'CRBN 1X Power Series 16mm',
    preferred_side: 'flexible',
    join_date: '2024-01-18',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🎓 Huấn Luyện Viên Tâm Huyết', '🏆 Bậc Thầy Chiến Thuật'],
    bio: 'Cố vấn chuyên môn và huấn luyện kỹ thuật đánh đôi cho các thành viên trong CLB Friends.',
  },
  {
    id: 'm25',
    full_name: 'Thế Quyền',
    nickname: 'Quyền Thế',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
    phone: '0901.009.988',
    email: 'thequyen@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'Gearbox Pro Power',
    preferred_side: 'left',
    join_date: '2024-03-10',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🚀 Quả Giao Bóng Uy Lực'],
    bio: 'Thể lực sung mãn, di chuyển bao sân tốt và giao bóng tốc độ cao.',
  },
  {
    id: 'm26',
    full_name: 'Trai Nhà Quê',
    nickname: 'Trai Nhà Quê',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    phone: '0912.998.877',
    email: 'trainhaque@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'Engage Pursuit Pro',
    preferred_side: 'flexible',
    join_date: '2024-03-01',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🌾 Đam Mê Bất Tận', '🔥 Đánh Hết Mình'],
    bio: 'Mộc mạc, nhiệt huyết và luôn cống hiến hết mình trong từng đường bóng.',
  },
  {
    id: 'm27',
    full_name: 'Tuan Nguyen',
    nickname: 'Tuan Nguyen',
    avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    phone: '0923.887.766',
    email: 'tuan.nguyen@friends.club',
    dupr_rating: 3.13,
    elo_points: 1050,
    role: 'member',
    hand: 'right',
    paddle: 'Head Radical Elite',
    preferred_side: 'right',
    join_date: '2024-03-15',
    matches_played: 0,
    matches_won: 0,
    matches_lost: 0,
    current_streak: 0,
    badges: ['🏸 Tay Vợt Đa Năng'],
    bio: 'Lối đánh toàn diện công thủ, luôn sẵn sàng tham gia các trận đấu đôi kịch tính.',
  },
];

export const INITIAL_TOURNAMENTS: Tournament[] = [];

export const INITIAL_MATCHES: Match[] = [];

export const INITIAL_NEWS: NewsPost[] = [
  {
    id: 'news_1',
    title: 'Khai mạc Giải Đấu "Friends Autumn Cup 2026" 🏆',
    content: 'CLB Pickleball Friends chính thức khai mạc giải đấu đôi Friends Autumn Cup 2026 tại cụm Sân Dũng/Vân Anh (Eko Lake - Linh Sơn - Thái Nguyên) với sự tham gia của 12 cặp đôi chia làm 3 bảng đấu hấp dẫn.',
    category: 'tournament',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
    author_name: 'Ban Tổ Chức CLB Friends',
    created_at: '2026-08-30T08:00:00Z',
    likes: 28,
  },
  {
    id: 'news_2',
    title: 'Lịch Giao Lưu & Sinh Hoạt Định Kỳ Tháng 9/2026',
    content: 'Lịch sinh hoạt cố định: Thứ 3, 5, 7 từ 18:00 đến 21:30 và sáng Chủ Nhật từ 07:30 đến 11:30 tại Sân Dũng/Vân Anh (Khu đô thị Eko Lake - Linh Sơn - Thái Nguyên). Thành viên đăng ký sớm để BTC sắp xếp ca đánh đôi và tính điểm DUPR/ELO.',
    category: 'schedule',
    image_url: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&q=80&w=800',
    author_name: 'Chủ Tịch Hoàng Mạnh Cường',
    created_at: '2026-08-28T14:30:00Z',
    likes: 22,
  },
  {
    id: 'news_3',
    title: 'Vinh Danh Cặp Đôi Xuất Sắc Nhất Tháng: Dương Tuấn Anh & Hoàng Mạnh Cường 🎉',
    content: 'Chúc mừng cặp đôi Dương Tuấn Anh & Chủ tịch Hoàng Mạnh Cường đã đạt thành tích xuất sắc, tạm dẫn đầu Bảng xếp hạng điểm ELO & DUPR CLB Friends.',
    category: 'recap',
    image_url: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a29?auto=format&fit=crop&q=80&w=800',
    author_name: 'Ban Chuyên Môn',
    created_at: '2026-08-26T09:15:00Z',
    likes: 42,
  },
];

export const INITIAL_JOIN_REQUESTS: JoinRequest[] = [
  {
    id: 'req_1',
    full_name: 'Nguyễn Văn Hùng',
    phone: '0909.888.777',
    zalo_fb: 'https://zalo.me/0909888777',
    self_rating: 3.0,
    experience_years: '1 năm',
    preferred_hand: 'Tay phải',
    message: 'Mình muốn tham gia CLB Friends để giao lưu đánh đôi 2v2 buổi tối tại sân Dũng/Vân Anh và nâng cao trình độ DUPR.',
    status: 'pending',
    created_at: '2026-08-31T09:00:00Z',
  },
];

export const INITIAL_SETTINGS: ClubSettings = {
  club_name: 'Friends Pickleball Club',
  slogan: 'Đam Mê - Kết Nối - Nâng Tầm Trình Độ 🎾⚡',
  location: 'Sân Dũng/Vân Anh, địa chỉ: khu đô thị Eko Lake - Linh Sơn-Thái Nguyên',
  play_schedule: 'Thứ 3, 5, 7: 18h00 - 21h30 | Chủ Nhật: 07h30 - 11h30',
  contact_phone: '0988.112.233 (Chủ tịch Hoàng Mạnh Cường)',
  contact_zalo: 'https://zalo.me/g/picklefriends',
};
